name: Deploy to demo-server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to server and update the deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 49.13.230.22
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY_3 }}
        script: |   
          cd ~/demo/Rox_Chain_Explorer
          git pull
          docker rm -f rox-chain-explorer
          docker build -t rox-chain-explorer
          docker run -d -p 2004:3000 --name=rox-chain-explorer --restart=unless-stopped rox-chain-explorer
